name = "animal-website"                # Worker name
compatibility_date = "2026-01-02"      # Todayâ€™s date
type = "javascript"

[site]
bucket = "./"                           # Folder containing all your HTML, CSS, JS, images
entry-point = "workers-site"            # Default for workers-sites
